name: CI

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '*'

jobs: 
  check: 
    name: Check
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout sources
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@29eef336d9b2848a0b548edc03f92a220660cdb8 # stable

      - name: Run cargo check for lib
        run: cd confidence && cargo check

      - name: Run cargo check for demo
        run: cd demo && cargo check

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@29eef336d9b2848a0b548edc03f92a220660cdb8 # stable

      - name: Run cargo test
        run: cd confidence && cargo test