on: 
    push: 
        branches: 
            - main

name: Run Release Please
jobs: 
    release-please: 
        runs-on: ubuntu-latest

    # Release-please creates a PR that tracks all changes
        steps: 
        - uses: google-github-actions/release-please-action@db8f2c60ee802b3748b512940dde88eabd7b7e01 # v3
          id: release
          with:
            release-type: simple
            command: manifest
            default-branch: main

        - name: Dump Release Please Output
          env:
            RELEASE_PLEASE_OUTPUT: ${{ toJson(steps.release.outputs) }}
          run: |
            echo "$RELEASE_PLEASE_OUTPUT"
        outputs:
          release_created: ${{ steps.release.outputs.release_created }}

    rust-release:
        name: Publish (crates.io)
        needs: release-please
        if: ${{ needs.release-please.outputs.release_created }}
        runs-on: ubuntu-latest
        timeout-minutes: 25
        steps:
          - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

          - name: Install stable toolchain
            uses: dtolnay/rust-toolchain@29eef336d9b2848a0b548edc03f92a220660cdb8 # stable

          - name: cargo login
            run: cargo login ${{ secrets.PUBLISH_CRATE_TOKEN }}
          - name: "cargo release publish confidence"
            working-directory: confidence
            run: |-
              cargo publish

          - name: "cargo release publish openfeature provider"
            working-directory: provider
            run: |-
              cargo publish
